TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#
#----------------------------------------------------
# Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
DB += devTprInfo.db
DB += pcie_tprTrig.db
DB += pcieSlave_tprTrig.db
DB += tprTrig.db
DB += tprTrig6.db
DB += tprTrig8.db
DB += tprTrig_ued.db
DB += tprTrig_smrf.db
DB += tprDeviceNamePV.db



#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
#
